* ~guix-env~

An environment configured to my liking for use with ~guix home~.

This is quite preliminary thus far. To smooth off some of the currently rough
edges, either I or people working on ~guix home~ need to do some more work.
Current issues include:
- Fish shell does not allow setting the environment variable ~_~.
- ~guix home reconfigure~ needs ~--allow-downgrades~ (not sure about this one).
- Dotfile repositories get pulled anew on every new container started.
- The `home-fish-service-type` clashes with a custom dotfile repository, though
  I was able to work around this though the code in ~link-config.fish~.
- When invoking the environment as a container:
  - ~/bin/sh~ is not available (though ~sh~ is present at other locations).
  - There is a warning that the ~on-first-login~ script won't execute anything,
    because ~XDG_RUNTIME_DIR~ is not set.
  - It may be safer to start the container with ~sh~/~bash~ as login shell
    instead of ~fish~, as there are some additional errors and warnings in the
    latter case.
