#!/bin/sh

# NOTE: It seems that this is not necessary, but it may depend on the callee.
#. $HOME/.profile

# NOTE: Depending on what program executes this file, `$HOME/.xsession-errors`
# might not be created.
exec xmonad
